joshwcomeau/guppy

src/base.css, src/components/Button/Button.js, src/index.js
I add an initial color to the button to solve a problem with colors in the dark mode of macos mojave since the button on the intro screen looks white with the white text because in the darkmode the default text is white.
I tested the project at my place and putting an initial dark color on the button fixes this and it has no problem since the colors of the other states of the button are well defined depending on the conditions in which it is used.
=> Add an initial color to Button

src/components/CreateNewProjectForm/CreateNewProjectForm.js, src/utils.js
Remove unused import and refactor getTimeOfDay function
=> Remove unused import and refactor getTimeOfDay function

CONTRIBUTING.md
A few changes to the contribution docs:
- Rearrange so that "Sending a Pull Request" is closer to the top
- Add a "most important" blurb in the intro
- Add a "Collaborators" section
- A few other small tweaks
=> Update contribution docs

src/actions/index.js, src/components/AddDependencySearchResult/AddDependencySearchResult.js, src/components/DeleteDependencyButton/DeleteDependencyButton.js, src/components/DependencyUpdateRow/DependencyUpdateRow.js, src/components/DevelopmentServerPane/DevelopmentServerPane.js, src/components/TaskDetailsModal/TaskDetailsModal.js, src/components/TaskRunnerPane/TaskRunnerPane.js, src/middlewares/dependency.middleware.js, src/middlewares/import-project.middleware.js, src/middlewares/task.middleware.js, src/reducers/dependencies.reducer.js, src/reducers/dependencies.reducer.test.js, src/reducers/package-json-locked.reducer.js, src/reducers/paths.reducer.js, src/reducers/projects.reducer.js, src/reducers/tasks.reducer.js
**Related Issue**
Discussion about selectors in #97 pr
**Summary**
order of selectors arguments was changed, now the state is the first argument of selectors
=> order of selectors arguments was changed

README.md
=> Add copyright year suffix to README

src/reducers/paths.reducer.js, src/services/create-project-service.test.js, src/services/create-project.service.js, src/services/read-from-disk.service.js
I missed it in my review of `window-support`
=> defaultParentPath is a constant

src/actions/index.js, src/components/ApplicationMenu/ApplicationMenu.js, src/components/DevelopmentServerPane/DevelopmentServerPane.js, src/components/Module/Module.js, src/reducers/tasks.reducer.js
This pull request adds a new button to the top of the "Development Server" pane to clear the console. 
It looks like this:
=> "Clear Console" Button

.vscode/extensions.json, .vscode/settings.json
**Summary:**
This is highly subjective, it's just some of the settings that make me more productive so I thought I'd share. Feel free to close if you don't like it tho.
=> improve a bit the DX on vscode

scripts/start.js, src/components/Sidebar/Sidebar.js, src/main.js, src/reducers/projects.reducer.js, src/reducers/projects.reducer.test.js, src/store/storage-engine.js
**Summary:**
Couple bugs creeped in recently, this PR addresses them. Described more inline.
=> Fix selection bug, add electronStore to window

src/main.js
In #176, @AWolf81 suggested I add better logging to `main.js` with Chalk. I did this change, but neglected to push it to github 😅
Quick subsequent PR to implement it.
=> Add better logging to main.js

src/actions/index.js, src/reducers/paths.reducer.js, src/reducers/projects.reducer.js, src/sagas/delete-project.saga.js, src/sagas/delete-project.saga.test.js
#170
**Summary:**
This is the flow for deleting a project from the Guppy app, but keeping it on disk 😄
=> Delete project from guppy

docs/dev-info/code-structure.md
Quick PR to make the tweaks @j-f1 suggested in #157
=> Add proper links to code-structure

src/sagas/delete-project.saga.js, src/sagas/delete-project.saga.test.js
Small tweak to the delete prompts
=> Add newlines to delete prompt

src/store/index.js, src/store/migrations.js, src/store/migrations.test.js
**Related Issue:** closes #178 
**Summary:**
Add our very first migration (🎉), which'll enable current users to update to 0.3 without losing all their projects (🎉🎉🎉).
=> Add migration from zero to one

src/__mocks__/electron-store.js, src/main.js, src/reducers/dependencies.reducer.test.js, src/reducers/projects.reducer.test.js, src/reducers/tasks.reducer.test.js, src/sagas/development.saga.js, src/sagas/development.saga.test.js, src/services/electron-store.service.js, src/store/storage-engine.js
Buncha fixes for various test issues, described inline.
=> Test cleanup and repair

src/actions/index.js, src/components/App/App.js, src/components/CreateNewProjectWizard/CreateNewProjectWizard.js, src/components/CreateNewProjectWizard/ProjectPath.js, src/components/FormField/FormField.js, src/components/ProjectConfigurationModal/ProjectConfigurationModal.js, src/components/ProjectPage/ProjectPage.js, src/components/SelectableImage/SelectableImage.js, src/components/SettingsButton/SettingsButton.js, src/reducers/modal.reducer.js, src/reducers/paths.reducer.js, src/reducers/projects.reducer.js, src/reducers/tasks.reducer.js, src/sagas/save-project-settings.saga.js, src/services/create-project.service.js, src/types.js, yarn.lock
Made some visual tweaks to @AWolf81's Project Configuration modal.
I also discovered and fixed some bugs while I was working on it, and made a few quick refactors.
New animation on button:
New button:
=> Visual tweaks and bugfixes for Project Configuration Modal

src/components/TaskDetailsModal/TaskDetailsModal.js, src/components/TaskRunnerPane/TaskRunnerPane.js, src/components/TaskRunnerPaneRow/TaskRunnerPaneRow.js, src/reducers/tasks.reducer.js, src/reducers/tasks.reducer.test.js, src/store/migrations.js, src/store/migrations.test.js, src/types.js
**Related Issue:** #86 
**Summary:**
=> Update tasks.reducer to use a nested structure

src/__mocks__/electron-store.js, src/components/App/App.js, src/sagas/analytics.saga.js, src/sagas/index.js, src/services/analytics.service.js, src/services/analytics.service.test.js
**Related Issue:** #242 
**Summary:**
Added the saga to track a number of user actions
=> Add saga for analytics

package.json, src/components/AvailableWidth/AvailableWidth.js, src/components/AvailableWidth/index.js, src/components/CreateNewProjectWizard/BuildPane.js, src/components/CreateNewProjectWizard/CreateNewProjectWizard.js, src/components/CreateNewProjectWizard/MainPane.js, src/components/CreateNewProjectWizard/SummaryPane.js, src/components/CreateNewProjectWizard/types.js, src/components/Planet/Orbit.js, src/components/Planet/PlanetCloud.js, src/components/WhimsicalInstaller/File.js, src/components/WhimsicalInstaller/WhimsicalInstaller.helpers.js, src/components/WhimsicalInstaller/WhimsicalInstaller.helpers.test.js, src/components/WhimsicalInstaller/WhimsicalInstaller.js, src/components/WhimsicalInstaller/WhimsicalInstaller.stories.js, src/components/WhimsicalInstaller/WhimsicalInstaller.types.js, src/reducers/dependencies.reducer.test.js, src/store/migrations.test.js, yarn.lock
Work continues on the whimsy installation easter egg!
This diff adds the ability to "throw" a file after catching it:
=> Whimsy install - Released files

src/components/CreateNewProjectWizard/MainPane.js, src/components/ProjectConfigurationModal/ProjectConfigurationModal.js, src/components/ProjectIconSelection/ProjectIconSelection.js, src/components/ProjectIconSelection/ProjectIconSelection.stories.js, src/components/ProjectIconSelection/index.js, src/utils.js
#232 
**Summary:**
I created a new component called `ProjectIconSelection` and replace it in two part where it was used.
=> Add project icon selection component

PRIVACY.md, src/components/ApplicationMenu/ApplicationMenu.js
**Related Issue:** closes #242 
**Summary:**
The final step for our analytics, this diff:
- Creates a Privacy Policy README
- Links to it from within the app, through the ApplicationMenu
=> Add privacy policy

src/components/CircularOutline/CircularOutline.js
quick example of what it could look like (written in the github editor so it probably doesn't work)
=> allow an arbitrary number of color stops

src/main.js
**Summary:**
Fixed the enabling of chrome extensions in the development environment.
=> Changed setting to enable Chrome extensions in the dev enviroment

package.json, src/components/Sidebar/Sidebar.js
In response to issue #262
**Summary:**
Adds scrollbars if needed to the sidebar
Used the recommended package http://malte-wessel.github.io/react-custom-scrollbars/
Had to do some minor tweaks to keep styling and to disable horizontal scrolling
=> Add scrollbar in projects' sidebar

src/components/Sidebar/Sidebar.js, yarn.lock
#262 
**Summary:**
I think the scrollbar was a bit too dark and I've also added a border radius to the thumb.
I've added `transitionFlip={false}` to remove the jitter during scrolling. Still the moving of the tooltip is not perfect but the weird tooltip seems to be fixed.
I played with the tooltip duration, animation & sticky but nothing changed the update behaviour of the tooltip. The tooltip should stick at the display location & hide after a small delay.
Transparent white bar so it's similar to the icons
=> Changed scrollbar styling inside Sidebar

src/components/LoadingScreen/index.js
**Summary:**
Quick fix as there was one flow annotation missing. 
Fails because of the new check introduced by the merged branch from @mathieudutour.
=> Flow annotation

src/components/Sidebar/Sidebar.test.js
#309
**Summary:**
Added test for `componentWillReceiveProps` to increase test coverage.
I know that we should change that hook and remove the timeouts by moving them to `componentDidUpdate` to avoid `setTimeouts` (as mentioned in the comment).
During writing that test I've noticed that there are many re-renders over 1000 times (see screenshot from coverage report below). So there could be a performance problem but I haven't checked. Or am I misinterpreting this? Is it just telling that that line is covered that often?
I think we should open an issue for the refactoring of the timeouts and to check the performance.
=> Increase Sidebar test coverage

src/components/TaskRunnerPane/TaskRunnerPane.js, src/components/TaskRunnerPane/TaskRunnerPane.test.js
#309
**Summary:**
- Test rendering (tasks list & modal)
- Test component logic
- Unselect task if it's removed from tasks list
- Test task toggle (`runTask` or `abortTask`)
- Dismiss task details view
=> Test TaskRunnerPane component

src/services/create-project.service.js, src/services/create-project.service.test.js
**Summary:**
Added tests for project creation service.
- Fake project creation test
- Folder check & creation test
- Event listening (stdout, stderr, close) test
- CRA commit test
=> Test create project service (Improve coverage)

.flowconfig, package.json, src/actions/index.js, src/components/App/App.js, src/components/Sidebar/Sidebar.js, src/components/Sidebar/Sidebar.test.js, src/components/Sidebar/SidebarProjectIcon.js, src/components/Sidebar/SidebarProjectIcon.test.js, src/reducers/__snapshots__/projects.reducer.test.js.snap, src/reducers/projects.reducer.js, src/reducers/projects.reducer.test.js, yarn.lock
Based on branch from @beyersito (see PR #310).
I'm comandeering this to get this ready. 
I think this is ready for review - I just need to find the offset issue that occurs if icon is dragged with a scrolled sidebar (see third screenrecording)
#195 
**Summary:**
- Rebased to master (Reorder projects was using React-Motion - so this rebase changed a lot of the branch & hopefully I've fixed everything.)
- Added review comments & fixed scroll behaviour
**Drag & drop with fullscreen window**
**Drag & drop reduced window size (not scrolled)**
**Drag & drop reduced window size (scrolled) - y-offset issue**
**Todo**
=> Feature reorder projects

src/components/App/App.js
=> Conditional for Titlebar component
