joshwcomeau/guppy

src/components/DependencyDetailsTable/DependencyDetailsTable.js, src/reducers/dependencies.reducer.js, src/types.js
I thought this would be a simple case of changing the reference from repository to repository.url but since some packages (like Gatsby) have a url with git+https protocol it wasn't quite so simple.
I'm not super experienced with react and I have a feeling I'm doing too much at the top of the render function here. Should this be a utility function instead? In the module top level or on the class? Something like this:
```javascript
parseRepositoryURL = dependency => {
try {
let githubURL = new URL(dependency.repository.url);
githubURL.protocol = 'https';
return githubURL.href;
} catch (e) {
return null;
}
};
//...
render () {
const githubHref = parseRepositoryURL(dependency);
//...
```
I also changed the  repository type from string to a {type: ..., url: ...} object in the flow types and …
=> fix #48: get the repo url from package.json

src/actions/index.js, src/middlewares/import-project.middleware.js, src/reducers/onboarding-status.reducer.js
This attempts to fix #62 where importing unsupported projects was throwing you into a blank screen. 
My solution was to add an action that handles the error (basically just mimicking CREATE_NEW_PROJECT_CANCEL). This keeps onboarding status to 'brand new' so when you exit out of the error prompt, you're kept on the start screen.
=> Add action to make unsupported project errors fail gracefully

src/components/ApplicationMenu/ApplicationMenu.js
As referenced in #72 this ensures proper text field behavior (undo/redo, copy/paste, quick emoji picker🐠) on macOS. Do linux and windows currently show the menu?
=> add Edit menu

src/middlewares/import-project.middleware.js
When testing out Import Existing, all my projects with package.json were getting the proper `Unsupported project type` error, whereas one in particular was getting `Unknown error`, despite it having a package.json.
I realized it was because this project actually didn't have a dependencies key in its package.json at all, and therefore was returning undefined.
Just added a simple check to make sure there's the `json.dependencies` key so the error message is consistent across unsupported projects with package.json.
However, we could also probably have some sort of check to cover not having a package.json at all. Not having a package.json isn't technically an `Unknown error`, right? Not having a package.json means the project by default cannot be a React or Gatsby project.
Or is that too …
=> Check for json.dependencies when running inferProjectType

src/components/DependencyManagementPane/DependencyManagementPane.js
If the last dependency in DependencyManagePane is deleted, the application will crash as it doesn't update selectedDependencyIndex to be in range for the newly shortened list.
=> fix crash when deleting last dependency in list

src/components/AddDependencySearchResult/AddDependencySearchResult.js, src/components/CustomHighlight/CustomHighlight.js, src/components/CustomHighlight/index.js, src/utils.js
I wanted to create a separate branch and open this for discussion. This attempts to address item 4 in #80
I was able to get highlighting working by creating a CustomHighlight with the `_highlightResult` key, however it appears that dangerouslySetInnerHTML is still needed to actually render the HTML (rather than leaving it escaped per item 1 in #80). So the question still remains if dangerouslySetInnerHTML is the way to go here?
=> Add support for highlighting results

src/components/AddDependencySearchResult/AddDependencySearchResult.js, src/components/Button/Button.js, src/components/ExternalLink/ExternalLink.js
Fixes 1 and 2 from the list in #80
- ~Unescapes the package description with `dangerouslySetInnerHTML`. I'm a bit unsure about this due to the obvious security concerns. What do people think?~
- Fixed the formatting issues inside the <Header> (wrapping, positioning etc).
- Added styling for `.ais-InfiniteHits-loadMore--disabled` so there's no confusion about it not loading more when there's no more results to load.
=> Fix html display in dependency search, and styling tweaks for results

src/components/TaskRunnerPane/TaskRunnerPane.js, src/middlewares/task.middleware.js
Thanks for your contribution!
Please fill out the following template with details about your pull request:
**Related Issue**
#25 
**Summary**
Thanks to @superhawk610's great suggestion, we no longer have to rely on `echo` to send a command to the running process. Yay unblocking windows support!
Incidentally, fixing this issue exposed a bug, which is that Guppy crashes when ejecting a project while the "View Details" modal is open. This is because the modal assumes a `task` will be provided, but the eject task removes itself. 
The fix is simply to unset the `selectedTaskId` state when the task is deleted. This feels like maybe it should move to Redux, since deriving state from props like this is discouraged... but I'm happy enough with this solution for now.
=> Bi directional communication

src/reducers/dependencies.reducer.test.js, src/services/create-project-service.test.js, src/services/create-project.service.js, src/services/location.service.test.js, src/services/project-name-service.test.js, src/services/project-name.service.js, src/services/project-type-specifics.test.js
**Related Issue**
#41 @joshwcomeau requested some tests to be written for the more important files/functions
**Summary**
Adding tests for some of the services/modules:
For the Project Name service, I had to export the prefixes and suffixes array to test against this list given the format we output. Let me know if you guys think this is an appropriate way to test this.
I did also add some tests for the `create-project.service.js`, but it doesn't test all of the contained functions (just the easy ones 😝). I did have to mock a few things, but maybe this mocking should live somewhere else, instead. WDYT?
There was a test that was failing for me locally in the `dependencies.reducer.test.js`, so I updated it. If that's not okay, I can revert that change.
=> Adds more tests for untested services

.github/PULL_REQUEST_TEMPLATE.md
@j-f1 suggested we use HTML comments in our issue templates, and I thought it'd be good to follow that pattern in PRs.
=> Use comments in PR template

src/components/DeleteDependencyButton/DeleteDependencyButton.js, src/components/DependencyDetails/DependencyDetails.js, src/components/ModalHeader/ModalHeader.js, src/components/PixelShifter/PixelShifter.js, src/components/ProjectPage/ProjectPage.js
**Summary:**
While responding to a comment in #28, I saw a `<PixelShifter>` component, and it wasn't immediately clear to me what it was doing.
I added `<PixelShifter>` as a low-effort way to make subtle pixel tweaks for alignment, but I hadn't realized how inscrutable they'd be after a few weeks/months.
This PR adds a mandatory "reason" prop that can be used essentially as a comment (but because it's an actual prop, we can insist that it's supplied*)
* Weirdly, Flow doesn't seem to mind if it's omitted :/ it tells me "No errors" when I don't add it. It also says "No errors" when I do something totally wrong like `y="hello"`. So Flow appears to not be working properly on this component?
Both files (the `PixelShifter` component and its callsite) have `// @flow` enabled, so I'm completely …
=> Add 'reason' to PixelShifter

config/webpack.config.dev.js, config/webpack.config.prod.js, src/components/ApplicationMenu/ApplicationMenu.js, src/components/DeleteDependencyButton/DeleteDependencyButton.js, src/components/EjectButton/EjectButton.js, src/components/ExternalLink/ExternalLink.js, src/components/HelpButton/HelpButton.js, src/middlewares/import-project.middleware.js, src/middlewares/task.middleware.js, src/reducers/paths.reducer.js, src/services/create-project.service.js, src/services/dependencies.service.js, src/services/find-available-port.service.js, src/services/read-from-disk.service.js, src/services/redux-persistence.service.js
**Summary:**
Webpack has a option to specify the target of the bundle as `electron` so that it knows that the nodejs built-in modules are ignored.
I also changed all the `window.require` to `import` so that flow knows how to deal with it.
=> setup proper target for webpack and use import everywhere

CONTRIBUTING.md
This was discussed on Gitter while releasing 0.2.0 but somehow managed to slip through the merge. `yarn package:{platform}` builds for release, while `yarn dist:{platform}` first creates the React bundle and *then* builds for release. This PR updates the contribution guidelines to indicate the correct script.
=> Use correct package script for release build

src/components/Button/Button.js, src/components/Button/Button.stories.js, src/components/DevelopmentServerPane/DevelopmentServerPane.js, src/components/Modal/Modal.js, src/components/PixelShifter/PixelShifter.js, src/components/TaskDetailsModal/TaskDetailsModal.js, src/components/TerminalOutput/TerminalOutput.js, src/components/WindowDimensions/WindowDimensions.js, src/components/WindowDimensions/index.js
**Summary:**
Earlier today, #57 was merged in. I had a couple extra things I wanted to do:
- Tweak the styling, because I'm nitpicky like that 😅Among some spacing tweaks, I set the button to be "filled" (the rough dichotomy in my head is that filled buttons mutate something / perform an action, whereas stroke buttons are just for showing information / opening modals).
- Add "clear" behaviour to the other terminal outputs, in the task detail modals.
- Tweak the "TaskDetailsModal" now that there's more stuff in it
Before: 
After: 
New details modal:
=> Add 'clear' button to TerminalOutput, tweak styles

scripts/start.js, src/main.js
This super-tiny change just removes `console.log` calls from around the codebase.
My philosophy is that `console.log` should only be used for temporary debugging statements. That way, when you're ready to open a PR, you can do a project-wide search for `console.log` and quickly clean them up.
`console.info` works just the same way as `console.log`, and feels a bit more semantic to boot. I also switched to `console.error` when the output was an error.
=> Remove console.log calls

src/components/ModalHeader/ModalHeader.js, src/components/TaskDetailsModal/TaskDetailsModal.js
**Summary:**
Two style tweaks that were bugging me:
- TaskDetailsModal now has smaller/lighter sub-headers. Felt way too prominent.
- The AddDependencyModal search input was too narrow, it ought to stretch the entire header.
I know these are really nitpicky / not high-priority, but whatever 🤷‍♀️ I really wanted to fix it!
TaskDetailsModal, before/after:
AddDependencyModal, before/after:
=> Fix modal header styling

package.json, src/sagas/import-project.saga.test.js, src/sagas/index.js, src/sagas/task.saga.js, src/sagas/task.saga.test.js, src/services/platform.service.js, src/store/configure-store.dev.js, src/store/configure-store.prod.js, yarn.lock
**Related PR:**
#111
**Summary:**
> I'm developing from a Windows machine, so I had to use @bennygenel's `windows-support` fork, and there are a few artifacts of that remaining in this code, but I figure the full redux-saga refactor is still a little ways off and with any luck we'll have Windows support merged into the master by then. If you'd like to run this yourself, it should be sufficient to just pull in `src/services/platform.services.js` from @bennygenel's repo [here](https://raw.githubusercontent.com/bennygenel/guppy/windows-support/src/services/platform.services.js). 
> I had to take an interesting approach to handling stdio channels within generator functions, so I'm curious if my `createStdioChannel` approach is the best way to go about this.
This PR takes the place of #111, …
=> Tasks middleware to saga

src/middlewares/task.middleware.js, src/reducers/tasks.reducer.js, src/reducers/tasks.reducer.test.js
**Related Issue:** #143
**Summary:**
There are two different potential states that we were treating the same:
- The server hit an error but is still running (eg. syntax error in userland code)
- Server crash (eg. can't find babel modules)
The bug was because we assume that "failed" for long-running tasks means that the server is still running, it's just waiting for the user to fix the issue and save the file. In this case, though, the server had crashed and was no longer running.
I feel pretty icky about how we're managing statuses, the difference between short-term and sustained tasks, etc. The whole thing could use an overhaul, but I still don't know exactly what the mental model should be... Maybe we should have an `isRunning` boolean in addition to states like `success`, `idle`, …
=> Fix issue with long-running task failure

src/actions/index.js, src/components/ApplicationMenu/ApplicationMenu.js, src/middlewares/delete-project.middleware.js, src/reducers/projects.reducer.js, src/store/index.js
#90 and #140
**Summary:**
This is the functionality for deleting project from disk. Right now it lives in the Project app menu but will eventually also live in the modal from #120. And eventually it will also have 'Delete from Guppy' option as well. It will also need to be converted to a saga once #154 lands.
Right now things seem to be 99% working, but there's an annoying bug I can't seem to figure out where the circular animations are not firing consistently. If you delete a project that's anything but the first in the list it will run, but not the first in the list 😕
In this PR I've also tweaked the Project menu conditional slightly. It was originally only showing up if `selectedProjectId && devServerTask` and this was fine when it just had the clear log task, but …
=> [WIP] Delete project from disk

package.json, src/actions/index.js, src/components/App/App.js, src/components/DevelopmentServerPane/DevelopmentServerPane.js, src/components/ProjectPage/ProjectPage.js, src/components/TaskRunnerPane/TaskRunnerPane.js, src/reducers/app-loaded.reducer.js, src/reducers/index.js, src/reducers/onboarding-status.reducer.js, src/reducers/package-json-locked.reducer.js, src/reducers/paths.reducer.js, src/reducers/projects.reducer.js, src/reducers/projects.reducer.test.js, src/reducers/tasks.reducer.js, src/reducers/tasks.reducer.test.js, src/sagas/index.js, src/sagas/refresh-projects.saga.js, src/sagas/refresh-projects.saga.test.js, src/store/index.js, src/types.js, yarn.lock
**Related Issue:** #160 
**Summary:**
Some changes to redux persistence meant that the "Development Server" and "Tasks" panes aren't immediately available. This was causing content to jump around as the app loaded:
This change adds a new `app-loaded` reducer to track this, and to only fade the app in once the redux state has been rehydrated from electron-store, and the projects have been parsed on disk to find the tasks.
This fix actually worsened another pre-existing bug. Here's what it looks like now:
This grey-box is a weird AF browser-rendering issue. Because it's pre-existing/separate, it will be dealt with in a subsequent PR.
=> Smooth out app open (Part 1)

src/components/App/App.js, src/components/ApplicationMenu/ApplicationMenu.js, src/components/DependencyManagementPane/DependencyManagementPane.js, src/components/MountAfter/MountAfter.js, src/components/MountAfter/MountAfter.stories.js, src/components/MountAfter/index.js
**Related Issue:** closes #160
**Summary:**
As discussed in #160, there is some wackyness happening when the component initially mounts.
In #163, I solved the major part of the problem, which was the fact that boxes loaded at different times. That made an existing issue much more apparent, though; that of the annoying grey rectangle:
This turned out to be a super puzzling issue: when rendering a small button with a 2px dashed border, we get this huge grey box @_@.
This really seems like a Chrome rendering bug.
In fact, even when I float another div _on top_ of the app, the rendering bug breaks out of its z-index to show itself:
I have no idea what the cause of this issue is, but a somewhat-hacky solution is clear: just delay rendering the problematic component. For some reason, when it's …
=> Smooth out app open (Part 2)

scripts/start.js, src/components/Sidebar/Sidebar.js, src/main.js, src/reducers/onboarding-status.reducer.js, src/reducers/projects.reducer.js, src/reducers/projects.reducer.test.js, src/services/read-from-disk.service.js, src/store/storage-engine.js
**Summary:**
Our philosophy around state persistence recently changed.
Before, we wanted to treat state as ephemeral; you could clear state whenever you wanted, and Guppy would try and rebuild itself magically.
Now, we realized a better state is just to make state-persistence more dependable, so that the user should never have to clear state. They still can if there's an issue, but it should be less common, and so it doesn't matter so much if it's slightly more inconvenient.
As a result, we no longer want to scan and automatically add projects found in the projects directory.
This change brings a few benefits:
- No more weirdness with onboarding when clearing state
- Deleting projects from guppy, but not from disk, will be possible now!
- No weirdness around changing home directory
- I …
=> Stop scanning home directory for projects

src/components/App/App.js, src/main.js
**Related Issue:** #106
**Summary:**
Electron's ipcRenderer keeps track of all running tasks spawned by Guppy and ensures that they are killed before the app closes. However, reloading the app (using `View > Reload` or `View > Force Reload`) refreshes the window without killing any processes, orphaning all processes spawned up until that point.
This PR adds a listener to the `beforeunload` event that is fired just before the window is reloaded to kill all running processes.
=> Kill all running processes on window reload

src/store/index.js
Argh this is embarrassing, I used the wrong syntax for the blacklist (nested arrays are for nested data structures).
This fix makes it so that `task` and `appLoaded` data isn't persisted from session to session.
=> Fix blacklist

src/services/create-project.service.js
closes #190
**Summary:**
When creating a new project we run `npx gatsby new ...` and it sets the package.json name key to `gatsby-starter-default` (this is just how `gatsby new` behaves, nothing to do with Guppy). Small PR to fix it.
=> Fix name in package.json after new project creation

src/main.js, src/store/index.js
https://github.com/joshwcomeau/guppy/issues/185
**Summary:**
On the app ready hook, before the browser window creation, checks if guppy is already in the Applications folder and if not, shows a Message Box that allows the application to be moved. If canceled it will just resume its normal startup process. If accepted, the application will be closed, moved and then restarted without the message.
=> "Move to Applications folder" on Mac

src/sagas/import-project.saga.js
**Summary:**
More bug fixin'. If a project was previously removed from Guppy and re-imported, it already has a `guppy` key in package.json. We want to check for this because currently importing projects assumes it's never been in Guppy before, and sets guppy.name to json.name... which doesn't have spaces.
=> Check for guppy key in package.json

CONTRIBUTING.md
I noticed that "collaborators" wasn't an H2 like it should have been.
I also added a bit more detail on whether or not collaborators should work on the main repo or their own fork, since it's not clear what's best.
=> Quick tweak to contributing docs

src/components/ProjectPage/ProjectPage.js
#46
**Summary:**
Added two buttons to `ProjectPage` Component.
It uses `platform.service` for `getCopyForOpenInFolder` caption.
Also `shell.service` is used for executing the commands.
Styling needs to be discussed. I think the size and location is OK but I'm not sure with the color.
A hover effect is changing the background color to a slightly darker gray.
=> Added buttons for opening in editor & Finder to project page

src/components/AddDependencySearchResult/AddDependencySearchResult.js, src/components/Button/ButtonBase.js, src/components/Button/ButtonBase.stories.js, src/components/Button/FillButton.js, src/components/Button/FillButton.stories.js, src/components/Button/StrokeButton.js, src/components/Button/StrokeButton.stories.js, src/components/Button/index.js, src/components/ButtonWithIcon/ButtonWithIcon.js, src/components/CreateNewProjectWizard/SubmitButton.js, src/components/DeleteDependencyButton/DeleteDependencyButton.js, src/components/DependencyUpdateRow/DependencyUpdateRow.js, src/components/HoverableOutlineButton/HoverableOutlineButton.js, src/components/IntroScreen/IntroScreen.js, src/components/ProgressBar/ProgressBar.stories.js, src/components/ProjectPage/ProjectPage.js, src/components/TaskRunnerPaneRow/TaskRunnerPaneRow.js, src/components/TerminalOutput/TerminalOutput.js
**Summary:**
Our `Button` component was trying to do too many things.
We ran into this when adding "Open in X" buttons in #205 - we wanted a simple hover state, but there was no simple way to add it, because we'd have to figure out what that should mean for stroke buttons, even though we only needed it on a fill button.
This PR creates two new Button components, `StrokeButton` and `FillButton`. They both use the same low-level primitive `ButtonBase` component, but offer their own props and styles.
For the most part, styles are unchanged, with two exceptions:
- I added a "splat" effect to FillButton when it's active. Before we were simulating this with a border, but now it feels better.
- We were able to add the hover effect to "Open in X" buttons!
=> Refactor Button -> FillButton & StrokeButton

src/actions/index.js, src/sagas/dependency.saga.js, src/sagas/dependency.saga.test.js
Just a quick PR to unify the design pattern used for saga actions that start running a queue. I originally had separate action creators for each possible way to start a queue (`installDependencyStart`, `uninstallDependencyStart`), but I realized that it was functionally identical to just calling `startNextActionInQueue` and was less clear. This pattern is more maintainable, precise, and easy to adapt for future uses of the queue (e.g. - #120).
=> Unify pattern for queue starter actions

src/actions/index.js, src/components/CreateNewProjectWizard/BuildPane.js, src/components/CreateNewProjectWizard/CreateNewProjectWizard.js, src/components/CreateNewProjectWizard/MainPane.js, src/components/CreateNewProjectWizard/ProjectPath.js, src/components/TextButton/TextButton.js, src/reducers/paths.reducer.js, src/services/create-project.service.js, src/services/create-project.service.test.js, src/services/read-from-disk.service.js, src/store/migrations.js, src/store/migrations.test.js
Add projectPath textInput to select projectPath in MainPane, This is convenient to select project directory for different project.
=> add the support of selecting projectPath when creating new project

src/components/Button/StrokeButton.stories.js, src/components/CreateNewProjectWizard/MainPane.js
I realized that my recent refactor in #209 broke the ProjectType outlines in the create-new-project wizard (they were always outlined, even when not selected).
Quick fix, just a matter of renaming the prop. Also added a story for strokeButton outlines.
=> Quick fix for ProjectType onboarding buttons

src/store/migrations.test.js
**Related Issue / PR**
#70 
**Summary:**
During my work on codecov CI I noticed that `migrations.test` failed if I run `yarn test` on Windows.
`Path.join` returns a backslash on Windows. That's why I added a mock to it so it's returning the expected path.
=> Fix migration test on Windows

src/components/CreateNewProjectWizard/CreateNewProjectWizard.js, src/components/CreateNewProjectWizard/MainPane.js, src/components/CreateNewProjectWizard/ProjectPath.js, src/services/create-project.service.js, src/store/migrations.js, src/store/migrations.test.js
In #70, @Kermit-Xuan  added a new "project path" field (and a bunch of associated work to tackle the redux side of things). The code looks great, but I wanted to make a couple visual tweaks.
Before: 
After:
A GIF of the new showing-ID behaviour:
=> Tweak visuals of project-path field

src/store/migrations.js
None, reported on Gitter by @shockry.
**Summary:**
The migration for `projectPath` throws an error on fresh clone. It can also be re-created by clearing state in console with `electronStore.clear()` and the re-freshing. (Not happening if done with the refresh menu item).
This is happening on master.
The error message is like following:
=> Quick fix to projectPath migration

src/store/migrations.test.js
Earlier, it was revealed that our migration tests weren't quite sufficient; they didn't accurately test how the migrations would work, when given state provided by the reducer, or by previous migrations!
This change adds a new pattern, which is that every `describe` block for a migration should include a test that:
- Starts with `initialState` created by running our root reducer
- Runs it through every previous migration function, in order.
For now, I think having the pattern in code is sufficient; we'll be monitoring changes to migrations closely, as they have the potential to break code for lots of people. If we find that migrations are slipping through review without solid tests, we can add some docs somewhere.
=> Add migration tests from initialState to current

src/components/ProjectConfigurationModal/ProjectConfigurationModal.js
`props.project` might be `null` in `ProjectConfigurationModal`
=> fix a bug when no project selected

src/sagas/task.saga.js, src/services/platform.service.js, src/services/platform.service.test.js
**Related Issue:** closes #30 
**Summary:**
Our terminal output hasn't been displaying the ANSI color codes that commands have been generating. This has led to very bland terminal output.
This change fixes that, by enabling an environment variable that includes those color codes, and then also fixes a display quirk by stripping out an unused control character.
=> Fix colors

src/components/ApplicationMenu/ApplicationMenu.js
#140
**Summary:**
Addressing the two open todos of the issue:
- Open settings
- Select Project submenu
I've added the open project settings button to the other opening commands. It opens the project settings modal. Accelerator Ctrl+, to match the other accelerators. I think there should be no collision with other keyboard shortcuts. 
Select project is using the native checkbox option from electron. So this could look different on other OS. The screenshot below is on Windows.
=> Added project selection & Show project settings to Application menu

src/actions/index.js, src/components/ProjectPage/ProjectPage.js, src/reducers/app-loaded.reducer.js, src/reducers/dependencies.reducer.js, src/reducers/dependencies.reducer.test.js, src/reducers/modal.reducer.js, src/reducers/onboarding-status.reducer.js, src/reducers/paths.reducer.js, src/reducers/paths.reducer.test.js, src/reducers/projects.reducer.js, src/reducers/queue.reducer.js, src/reducers/queue.reducer.test.js, src/reducers/tasks.reducer.js, src/reducers/tasks.reducer.test.js, yarn.lock
**Related Issue:** closes #246 
**Summary:**
Projects couldn't be deleted, as described in #246.
Additionally, this PR fixes an issue we've had with our tests: they weren't actually getting "realistic" initial state, since default values aren't used when you supply `undefined`. I updated all the reducers to make the `action` argument optional, so that the tests could actually use the initial state by running `reducer()`
=> Fix delete

src/components/CircularOutline/CircleOutline.stories.js, src/components/CircularOutline/CircularOutline.js, src/components/CircularOutline/CircularOutline.stories.js
**Related Issue:** #187 
**Summary:**
OK So I've fixed the issue it by making the CircularOutline <Rect> 100% of the parent SVG (and that is 100% of the parent div size).
I think we can remove all "width" props from this component now; does that seem right? I am still pretty new to this :)
We will have to keep the height because that determines the  values for `rx` and `ry`.
=> Fix for #187 (Dynamic button width breaks outline)

package.json, src/components/AvailableWidth/AvailableWidth.js, src/components/AvailableWidth/index.js, src/components/CreateNewProjectWizard/BuildPane.js, src/components/CreateNewProjectWizard/CreateNewProjectWizard.js, src/components/WhimsicalInstaller/File.js, src/components/WhimsicalInstaller/WhimsicalInstaller.helpers.js, src/components/WhimsicalInstaller/WhimsicalInstaller.helpers.test.js, src/components/WhimsicalInstaller/WhimsicalInstaller.js, src/components/WhimsicalInstaller/WhimsicalInstaller.stories.js, src/components/WhimsicalInstaller/WhimsicalInstaller.types.js, yarn.lock
This diff addresses feedback from previous diffs:
- Changes `swallowed` and `being-inhaled` to `captured` and `being-captured`
- Changes `fileSpeed` to be based on the width of the installer
- Adds a new AvailableWidth helper to figure out how large the WhimsicalInstaller should be
- Removes the "fade in" on the installer, since it's distracting and unnecessary
- Creates a new `types` file, instead of bundling them in `helpers`.
- Adds some helpful comments
This is the last PR in a sequence:
1 - Creating the original components - https://github.com/joshwcomeau/guppy/pull/215
2 - Allowing them to be "thrown" - https://github.com/joshwcomeau/guppy/pull/218
3 - Implementing it in BuildPane - https://github.com/joshwcomeau/guppy/pull/224
4 - This PR, finishing touches
Let me know what y'all …
=> Whimsy install - finishing touches

package.json, src/components/AvailableWidth/AvailableWidth.js, src/components/AvailableWidth/index.js, src/components/CreateNewProjectWizard/BuildPane.js, src/components/CreateNewProjectWizard/CreateNewProjectWizard.js, src/components/CreateNewProjectWizard/MainPane.js, src/components/CreateNewProjectWizard/SummaryPane.js, src/components/CreateNewProjectWizard/types.js, src/components/Planet/Orbit.js, src/components/Planet/PlanetCloud.js, src/components/WhimsicalInstaller/File.js, src/components/WhimsicalInstaller/WhimsicalInstaller.helpers.js, src/components/WhimsicalInstaller/WhimsicalInstaller.helpers.test.js, src/components/WhimsicalInstaller/WhimsicalInstaller.js, src/components/WhimsicalInstaller/WhimsicalInstaller.stories.js, src/components/WhimsicalInstaller/WhimsicalInstaller.types.js, src/reducers/dependencies.reducer.test.js, src/store/migrations.test.js, yarn.lock
This is the almost-final PR for my whimsical installer!! :D
It implements it in the build pane:
I'll have 1 more PR after this, which tackles:
- Seeing about using ResizeObserver in WhimsicalInstaller to avoid needing the fade-in delay in BuildPane
- Adds an `AvailableSpace` helper component which figures out how much width/height is available in a container, and passes it down with a render prop. This way, BuildPane doesn't have to specify an arbitrary width for the WhimsicalInstaller element, it can just fill the available space.
- Renames `being-inhaled` to `being-captured`, and `swallowed` to `captured`, from @j-f1's feedback in #215
=> Whimsy install - Add to build pane

src/components/ProjectConfigurationModal/ProjectConfigurationModal.js, src/components/ProjectPage/ProjectPage.js, src/components/TaskDetailsModal/TaskDetailsModal.js, src/components/TaskRunnerPane/TaskRunnerPane.js, src/components/TaskRunnerPaneRow/TaskRunnerPaneRow.js, src/components/Toggle/Toggle.js, src/components/Toggle/Toggle.stories.js, src/reducers/dependencies.reducer.js, src/reducers/queue.reducer.js, src/reducers/tasks.reducer.js
closes #49 
**Summary:**
When installing/deleting/updating dependencies, we shouldn't allow builds to be started; they'll likely fail, as the project's `node_modules` are updated during the process.
This change disables the "build" toggle while the project has an active item in the queue.
Note that it doesn't affect it the other way around; you can still start installing dependencies while a build is in progress. I think we should create another issue to track it separately, to keep this PR small.
I also took the liberty to add Toggle stories.
**Test Plan:**
- Install a new dependency. Verify that the "Build" toggle is disabled (both in TaskRunnerRow, as well as TaskDetailsModal). Try clicking it.
- Make sure the "Build" toggle turns back on afterwards
- Delete the new …
=> Disable build while the queue is active

.vscode/extensions.json
#255 
**Summary:**
Just adding a suggested VScode extension to add styled-components syntax highligthing
=> Add vscode styled-components syntax hightlighing

src/components/ProjectIconSelection/ProjectIconSelection.js, src/components/TaskRunnerPaneRow/TaskRunnerPaneRow.js, src/sagas/task.saga.js, src/sagas/task.saga.test.js
#68
**Summary:**
Addressing the issue where ejecting causes `babel-loader` to not be found. Didn't see anyone working on it so thought I'd take a stab at it!
Tests are failing but thought I'd get some feedback first before attempting to fix them, in case this approach isn't quite right...
**Test Plan:**
1. Create a test CRA project
2. Click `eject`
3. Task will run (with pending spinner) while promise is resolving. Once it's resolved, then the rest of the tasks will run (task pane will get deleted, dependency list will be updated which exposes `babel-loader` to the list because it's now installed)
Not sure if we want to modify things because right now there's a 'View Details' button in the UI for the eject task, but nothing gets piped to it. We may want to pipe all the …
=> [WIP] Install after eject

package.json, src/components/AddDependencySearchResult/AddDependencySearchResult.js, src/components/Button/ButtonBase.js, src/components/Button/StrokeButton.js, src/components/CircularOutline/CircularOutline.js, src/components/CircularOutline/CircularOutline.stories.js, src/components/DetectActive/DetectActive.js, src/components/DetectActive/index.js, src/components/HoverableOutlineButton/HoverableOutlineButton.js, src/components/SelectableItem/SelectableItem.js, src/components/Sidebar/AddProjectButton.js, src/components/Sidebar/SidebarProjectIcon.js, yarn.lock
**Related Issue:** closes #225 
**Summary:**
Our <CircularOutline> component triggered an immediate re-render after mount, since it needed to read the SVG created by React. This was causing performance issues (Stuttery modal opens, mostly). It was also causing a weird issue where the outlines would disappear sometimes, due to a Chrome bug (most likely).
This change creates a new division between two types of outlines:
- Truly circular ones, like the ones used in ProjectIcon. Round circles with an outline
- Outlined buttons, which are really just rounded rectangles
For the former, the behaviour is unchanged. This is possible because we know the width/height of those icons, so we can use geometry to work out the path length instead of relying on the DOM.
While it may be possible to do the …
=> Fix `CircularOutline` performance

src/components/CreateNewProjectWizard/BuildPane.js, src/components/CreateNewProjectWizard/CreateNewProjectWizard.js, src/components/CreateNewProjectWizard/MainPane.js, src/components/CreateNewProjectWizard/ProjectName.js, src/components/CreateNewProjectWizard/SubmitButton.js, src/services/create-project.service.js
#179
**Summary:**
Added a dialog before project creation starts if the project folder exists and blocks creation.
I don't like the overriding because a user could accidentally destroy an existing project.
I think blocking creation is OK as this is a rare use-case. 
=> Create project exists check

.circleci/config.yml, config/env.js, config/jest/babelTransform.js, config/jest/cssTransform.js, config/jest/fileTransform.js, config/jest/graphqlTransform.js, config/paths.js, config/polyfills.js, config/webpack.config.dev.js, config/webpack.config.prod.js, config/webpackDevServer.config.js, package.json, src/sagas/analytics.saga.test.js
#275
**Summary:**
- Added flow & lint check to Circle.CI
- Changed Flow check from `precommit` to `prepush`. So commiting is faster and pushing takes some time and for WIP pushs we can use `--no-verify`.
**Note:**
I think we should check if we're adding `node_modules` to flow ignore as we're checking over 45000 files. So we can be a lot faster with that ignore.
**Todos:**
=> Flow & lint CI config

package.json, src/sagas/delete-project.saga.js, src/sagas/delete-project.saga.test.js, yarn.lock
#277
**Summary:**
- Added [rimraf](https://www.npmjs.com/package/rimraf) for fast cross-platform delete 
- Splitted delete into two parts:
- Delete `node_modules` permanently as this can be restored from `npm`
- Move project to trash afterwards (as before)
Performance is better with-out freezing ~26sec now vs. before ~36sec . Deleting a project in terminal with rimraf takes 14sec. Not sure why it's slower in Guppy. File size in trash shrinked from ~120MB to 611kB for a newly created project.
One point we should do separately and we have to discuss is that we're needing a spinner that the delete is in progress as nothing is clickable during deletion (see screenrecording below). Just the application menu is clickable.
Maybe changing the mouse pointer to a glass would be …
=> Improve delete performance

src/reducers/dependencies.reducer.js, src/reducers/dependencies.reducer.test.js, src/reducers/onboarding-status.reducer.js
If you delete the entire projects folder, guppy will end up in a weird state where we show an empty sidebar.
This makes sure that if the onboarding state expect at least one project and that there is none, it gets reset
=> reset onboarding state when deleting project folder

src/components/TerminalOutput/TerminalOutput.js
**Summary:**
The "Clear" button was not consistent with the "Delete dependency" button
Before:
After:
=> consistent button color

src/components/Initialization/Initialization.helpers.test.js, src/components/Initialization/Initialization.js, src/main.js
#211
**Summary:**
- Added on close handling with IPC communication between mainWindow and renderer. Handled with channel `appWillClose` & `triggerClose`
- Created a pending task list to the modal that will be triggered if queue is not empty
**Todos**
**Things to discuss**
- Copy text OK, or should we modify something? Also is the information reduction OK? Or should we show what's installing/uninstalling?
- As mentiond `CreateProject` build process can be closed with-out dialog. We need to tackle this later as this transition state is not tracked yet.
- Is there an easier way to handle the dialog on exit? The problem is that we need to stop the event in the main process. That's why everything I've added in renderer/component wasn't working. 
=> Warn onexit about pending actions

src/services/create-project.service.js
Fixes #285
**Summary:**
Since CRA 2.0 automatically does a `git init` after project creation, the `package.json` with the Guppy info gets picked up as an uncommitted change, preventing functionality like Eject from running. 
Handling this is as simple as using exec to do a `git add` and `git commit`. The resulting git log for the project is:
```
commit 5664397208c9bda6110efd0f5755f6ccd54e4ea2 (HEAD -> master)
Author: Melanie Seltzer <melleh11@gmail.com>
Date:   Tue Oct 9 15:08:21 2018 -0700
Add to Guppy
commit 2014d676bff55e6d895722cc425b4a18ce1f1eca
Author: Melanie Seltzer <melleh11@gmail.com>
Date:   Tue Oct 9 15:08:21 2018 -0700
Initial commit from Create React App
```
I kept the commits separate but if we want to minimize the log, we could just do a `git commit …
=> Commit after CRA project creation

src/reducers/tasks.reducer.js, src/sagas/task.saga.js, src/sagas/task.saga.test.js
#285
**Summary:**
Checking git status before ejecting because ejecting will not work with a dirty repo. It's working as is but I'm classifying this as WIP because I wanted to get some opinions on a few things:
- @AWolf81 you mentioned adding a try/catch during eject but I wasn't clear where to add that (maybe I misread) - any thoughts after seeing this PR code?
- We needed some way to track whether the repo was clean (because the installation in the exit shouldn't run if ejecting failed due to repo being dirty). So I did this:
```js
emitter({
channel: uncleanRepo === true ? 'exit' : 'stderr',
text,
uncleanRepo,
});
```
Then used `uncleanRepo` in some if statements. Weirdly, I had to get super specific or it would always run the installation. For e.g. something like this …
=> [WIP] Check git status before ejecting

src/components/App/App.js, src/services/platform.service.js
We noticed when using the built application (with Electron Builder), Node wasn't found in the Path on MacOS, on computers that use NVM.
An issue with electron-builder (I think?) meant that the `.bashrc` file wasn't being sourced when creating new processes with `childProcess`.
`.bashrc` is _meant_ to be sourced for shells processes like this - NVM (Node Version Manager) assumes that it will be, and so that's where it adds the path to Node.
This change tries to read `.bashrc` when the app mounts, which updates the PATH based on stuff in that file.
This is a hacky fix, but to be honest, I just want to get 0.3 out. We can circle back to this and come up with a nicer fix later =)
=> Fix bundled Mac app

src/components/Initialization/Initialization.js
There is already a constant defined for the repo's URL so let's use it every where
=> use constant for the url of the repo

src/sagas/delete-project.saga.js, src/sagas/delete-project.saga.test.js
**Summary:**
Fixes failing test for new catch case in `delete-project.saga.`
Just one point is a bit hacky. But I'm not sure why I need to use `JSON.stringify` at `loadDependencyInfoFromDisk` test step.
=> Fixes failing test of delete-project.saga

src/actions/index.js, src/reducers/app-status.reducer.js, src/sagas/delete-project.saga.js, src/sagas/delete-project.saga.test.js
Fixes #279 
**Summary:**
Show a dialog to the user if the project delete fails for some reason.
I ended up wrapping rimraf + moveItemToTrash into a try/catch because I was getting `uncaught at callee` if I simply rejected with `false`. Not sure if this is good or if it should be structured differently.
Also, not sure I like that the fish spinner freezes while waiting for the dialog to get clicked. Is there a way around that or is that how it should be?
**To do**
**Screenshots**
=> Show dialog if project delete fails

src/components/Initialization/Initialization.js, src/services/platform.service.js, src/services/shell.service.js
Final fix for the electron-builder switch. Needed to reconfigure my `initializePath` method to return a promise, and then wait for it to complete before checking the Node version.
=> Initialize path before checking Node installation

src/components/DirectoryPicker/DirectoryPicker.js
Fixes #320
**Summary:**
Removing the leading slash was not working for me on Mac. Removing this behavior fixes the issue, but I am not sure why it was there in the first place. Is it necessary on Linux? Should we put it behind a check for OS?
=> Remove path.replace for leading slash

src/sagas/task.saga.js, src/sagas/task.saga.test.js
**Related PR:**
#318
**Summary:**
As discussed in the chat, have to remove `node_modules` after eject and before install, because it was not sensing there was anything to install ("Already up to date" output) and subsequently getting the previous dev server failure from missing packages.
=> Remove node_modules before install after eject

src/sagas/task.saga.js, src/sagas/task.saga.test.js
PR #331 identified the problem.
**Summary:**
If git state is dirty we need to update the UI to failed, so it's not pending forever.
Is there some way to not have the window refresh afterwards? Would be good if when the UI is updated, the window sits still so user isn't jumped up.
=> Update eject task UI to failed if git state dirty

src/components/TwoPaneModal/TwoPaneModal.js
As mentioned in PR #335 there is a small issue with the `ExternalLink` on the `LeftPane` of the TwoPaneModal.
**Summary:**
Added `pointerEvents` to `BackfaceWrapper`. If folded disable `pointerEvents`.
Styling of ExternalLink is unchanged - I've just used the recording from GatsbyStarter branch.
One point that could be improved is that the Earth animaion is running even if it's not visible (see recording below). I think the impact is not that big but I haven't tested. We can tackle this after this PR by adding a prop to `Earth` component so it's only animating if it's visible.
*With-out pointerEvents on BackfaceWrapper*
*With pointerEvents on BackfaceWrapper (different ExternalLink)*
*Removed class from div to show the Earth animation*
=> Added pointerEvents on BackfaceWrapper - fix hover issue

src/components/Button/StrokeButton.js, src/components/DetectActive/DetectActive.js
PR  #336 introduced a small visual issue in the project creation wizard.
**Summary:**
Changed wrapping `div` of `DetectActive` component back to `span`. 
Current master:
With fix:
=> Fix project type selection

package.json, src/components/BigClickableButton/BigClickableButton.test.js, src/components/BigClickableButton/__snapshots__/BigClickableButton.test.js.snap, yarn.lock
#309
**Summary:**
Two snapshot tests for button states.
Added [lolex](https://github.com/sinonjs/lolex) devDependency to mock `setTimeout` used by React-Spring. Otherwise every test run was creating a different snapshot because `_idleStart` changed.
We can remove `Lolex` later as it will be added to Jest but that's not ready yet. See link to PR in code comment.
=> BigClickableButton component test

src/components/Button/ButtonBase.js, src/components/Button/ButtonBase.test.js, src/components/Button/FillButton.js, src/components/Button/FillButton.test.js, src/components/Button/StrokeButton.js, src/components/Button/StrokeButton.test.js, src/components/Button/__snapshots__/ButtonBase.test.js.snap, src/components/Button/__snapshots__/FillButton.test.js.snap, src/components/Button/__snapshots__/StrokeButton.test.js.snap, src/components/ButtonWithIcon/ButtonWithIcon.test.js, src/components/ButtonWithIcon/__snapshots__/ButtonWithIcon.test.js.snap
#309 
**Summary:**
Most test cases are snapshot tests. For testing styled-components I've used `mount` so the styles are available in the snapshot. Not sure if there is a better way to test them but I think that's OK.
Added unit tests for:
- ButtonBase
- FillButton
- StrokeButton
- ButtonWithIcon
@idoberko2 would be awesome if you could also review these tests and let me know if there is something to improve.
I think next I'll add tests for `EjectButton` & `BigClickableButton` & for `ProjectConfigurationModal`. Probably in two PRs to separate them a bit as the `ProjectConfigurationModal` has more to test.
=> Test for button components

package.json
**Summary:**
As mentioned in this [post](https://vgpena.github.io/jest-circleci/) tried to increase works for coverage.
I've also configured CircleCi to 2 containers.
I'll add more details later today.
`--runInBands` not tested yet.  
Error about memory:
Not sure if the issue is fixed with `maxContainers` as I'm not seeing that there are two containers used. But the test passed.
=> CircleCi fails at reporting coverage (memory issue)

package.json, src/components/CreateNewProjectWizard/Gatsby/ProjectStarterSelection.js, src/components/CreateNewProjectWizard/Gatsby/ProjectStarterSelection.test.js, src/components/CreateNewProjectWizard/Gatsby/SelectStarterList.js, yarn.lock
#47
**Summary:**
After merging #335 I've noticed that entering an url or a starter name wasn't available. The `Summary` mentioned it but the functionality was removed because of the last UX improvement. Summary is correct again as the features are available once this PR is merged.
**Added the following to the input field:**
- Select starter by name e.g. enter `gatsby-starter-blog`
- Select stater by url e.g. `https://github.com/gatsbyjs/gatsby-starter-blog`
- Allow custom url with-out selecting a starter from the list e.g. `https://github.com/2manyprojects2littletime/gatsby-starter-blog`
- Test cases for the added functionality
**Discussion**
- Deleting the entered term in the input won't deselect the starter. I think that's OK - just wanted to mention it.
- Do we need …
=> [WIP] Improve Gatsby starter

src/components/DevelopmentServerPane/DevelopmentServerPane.js, src/components/DevelopmentServerPane/DevelopmentServerPane.test.js, src/components/DevelopmentServerPane/__snapshots__/DevelopmentServerPane.test.js.snap, src/components/Sidebar/Sidebar.js
#309
**Summary:**
- Test rendering (snapshot & no task rendered text)
- Test start / stop of devServer
=> Test DevelopmentServerPane component

package.json, src/components/DependencyManagementPane/DependencyDetailsTable.js, src/components/DependencyManagementPane/DependencyManagementPane.js, src/components/DependencyManagementPane/DependencyUpdateRow.js, yarn.lock
N/A
**Summary:**
Quick PR to fix some spacing issues I noticed (one of which caused a visual regression with Up-to-date verbiage). I think Prettier screwed up somehow? 
Also updated `lint-staged` config and pinned to 7.3.0 to get rid of this validation message I was seeing (see https://github.com/okonet/lint-staged/issues/482 for info):
=> Fix spaces and update lint-staged

src/components/AppSettingsModal/AppSettingsModal.js, src/components/AppSettingsModal/AppSettingsModal.test.js, src/components/AppSettingsModal/__snapshots__/AppSettingsModal.test.js.snap
#309
**Summary:**
Added tests for AppSettingsModal
- Updating `activeField`
- Saving newSettings
- Dialog test if path does't exists
- Snapshot for rendering
=> Test AppSettingsModal component

LICENSE.md
The title is not legally mandated, but it's convenient for human consumption, and provides additional metadata; for that reason, it is typically included in the template text of this license, as recommended by [OSI](https://opensource.org/licenses/isc-license), [SPDX](https://spdx.org/licenses/ISC.html#licenseText), [choosealicense.com](https://choosealicense.com/licenses/isc/), and others.
***Note**: This PR is part of my personal project to improve the consistency and visibility of the ISC license in open source projects. See https://github.com/github/choosealicense.com/issues/377 for more details.*
=> LICENSE: add title

src/components/ApplicationMenu/ApplicationMenu.js, src/locale/constants.js
[66](https://github.com/joshwcomeau/guppy/issues/66)
**Summary:**
According to ISO 639-1, "ch" stands for Chamorro and "zh" stands for Chinese.
Besides, I find that most apps use the original language for each language caption, for example, "Deutsch" for "de" and "中文" for "zh", so I think we'd better do it here too. What do you think?
=> Update languageCaptions in ApplicationMenu

src/components/Icons/index.js, src/components/ProjectPage/ProjectPage.js, src/components/ProjectTitle/ProjectTitle.js, src/components/ProjectTitle/ProjectTitle.stories.js, src/components/ProjectTitle/index.js, src/components/ProjectTypeSelection/ProjectTypeSelection.js
**Related Issue:** #319 
**Summary:**
- Added an icon that displays the icon for a project's type in the project title display
- Added project title to storybook
- Made the icon grayscale initially, then back to color on hover
- Added a tooltip that says what the project is.
- Refactored the icons in ProjectTypeSelection to be reused.
=> Project title icons

src/components/CreateNewProjectWizard/Gatsby/SelectStarterList.js, src/components/Heading/Heading.js, src/components/LoadingScreen/LoadingScreen.js, src/components/OnlineChecker/OnlineChecker.js, src/components/ProjectPage/ProjectPage.js, src/components/ProjectPage/__snapshots__/ProjectPage.test.js.snap
**Summary:**
Quick-fix of failing snapshot test. (I also fixed some linting warnings.)
The snapshot needed an update because of project type icon change in `ProjectPage` component.
=> Fix project page snapshot
